### ISSUE TITLE
/express-ffmpeg/views/default/index.jade:18 16| .push-box 17| .push-img > 18| a(href="/movie/#{pushmovie.movieid._id}") 19| if pushmovie.movieid.poster 20| img(src="#{pushmovie.movieid.poster}") 21| else Cannot read property '_id' of null

### ISSUE THREAD

**Issue by 721806280** [bookyo/express-ffmpeg#1]
/express-ffmpeg/views/default/index.jade:18 16| .push-box 17| .push-img > 18| a(href="/movie/#{pushmovie.movieid._id}") 19| if pushmovie.movieid.poster 20| img(src="#{pushmovie.movieid.poster}") 21| else Cannot read property '_id' of null

**Comment by bookyo** [comment]
清空推荐的表，这是因为你点了推荐又把视频给删了。

**Comment by ghost** [comment]
怎么清空推荐的表啊 后台管理没能看见 求助
